# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='文章标题')),
                ('describe', models.CharField(max_length=255, unique=True, verbose_name='文章描述')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='文章内容')),
                ('art_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserName', verbose_name='用户与文章的一对多关系')),
            ],
            options={
                'db_table': 'article',
            },
        ),
    ]
