# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='titlepic',
            field=models.ImageField(default=200, unique=True, upload_to='article'),
            preserve_default=False,
        ),
    ]
