# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-10 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.ImageField(upload_to='price'),
        ),
    ]
